language: node_js

# Keep empty to use version from .nvmrc
node_js: null

install:
  - npm ci

script:
  - npm run lint || travis_terminate 1;
  - npm run test || travis_terminate 1;
  - npm run build || travis_terminate 1;

after_success:
  - npx semantic-release

branches:
  only:
    - master

notifications:
  email: false
