sudo: false

language: node_js
node_js:

cache:
  directories: node_modules

install:
  - npm i

script:
  - npm run build
  - npx semantic-release

branches:
  only: master

notifications:
  email: false